
# A string used as a friendly name for your project
project_id = "cinohyzbtfzfcdtkgvij"

[functions]
[functions.initiate-call]
verify_jwt = false
import_map = "./import_map.json"

[functions.initiate-call.allowed_http_hosts]
"api.madrone.ai" = true

[http.headers]
Content-Security-Policy = "default-src 'self'; connect-src 'self' https://api.madrone.ai;"
