
# A string used as a friendly name for your project
project_id = "cinohyzbtfzfcdtkgvij"

[functions]

[functions.initiate-call]
verify_jwt = false

[[functions.initiate-call.allowed_http_hosts]]
host = "api.madrone.ai"

[functions.initiate-call.import_map]
path = "./import_map.json"
