
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { Resend } from "npm:resend@2.0.0";

const resend = new Resend(Deno.env.get("RESEND_API_KEY"));

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { recipientEmail, audioData } = await req.json();

    if (!recipientEmail || !audioData) {
      throw new Error("Missing required fields");
    }

    const emailResponse = await resend.emails.send({
      from: "AI Voice Assistant <onboarding@resend.dev>",
      to: [recipientEmail],
      subject: "🎧 Your AI Voice Clip",
      html: `
        <div style="font-family: sans-serif; color: #111;">
          <h2 style="color: #8B5CF6;">Your AI voice clip is ready 🎙️</h2>
          <p>Please find your voice clip attached to this email.</p>
          <p>Generated by your AI voice assistant.</p>
        </div>
      `,
      attachments: [
        {
          filename: 'voice-clip.wav',
          content: audioData,
          encoding: 'base64',
        },
      ],
    });

    console.log("Email sent successfully:", emailResponse);

    return new Response(
      JSON.stringify({ success: true, message: "Email sent successfully" }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 200,
      }
    );
  } catch (error) {
    console.error("Error sending email:", error);
    return new Response(
      JSON.stringify({ success: false, error: error.message }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 500,
      }
    );
  }
});
