
[build]
  publish = "dist"
  command = "npm run build"

# This ensures that all routes are handled by the single page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# These specific redirects are for custom URL changes
[[redirects]]
  from = "/ai-assistant"
  to = "/ai-receptionist"
  status = 301

[[redirects]]
  from = "/product-hunt"
  to = "/launch"
  status = 301

# Ensure privacy statement route works properly
[[redirects]]
  from = "/privacy-statement"
  to = "/index.html"
  status = 200

# Ensure the new routes work properly
[[redirects]]
  from = "/launch"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/demo"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/news"
  to = "/index.html"
  status = 200

# Add redirects for free voice agent URLs
[[redirects]]
  from = "/free-voiceagent"
  to = "/free-voice-agent"
  status = 301

[[redirects]]
  from = "/free-voice-agent"
  to = "/index.html"
  status = 200

# Add redirect for careers page
[[redirects]]
  from = "/careers"
  to = "/index.html"
  status = 200

# Add security headers to prevent Safari HTTPS notifications
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests"
