
[build]
  publish = "dist"
  command = "npm run build"

# This ensures that all routes are handled by the single page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Named redirects for specific route changes
[[redirects]]
  from = "/ai-assistant"
  to = "/ai-receptionist"
  status = 301

[[redirects]]
  from = "/product-hunt"
  to = "/launch"
  status = 301

[[redirects]]
  from = "/gpt"
  to = "/agent-gpt"
  status = 301

[[redirects]]
  from = "/demos"
  to = "/demo"
  status = 301

[[redirects]]
  from = "/free-voiceagent"
  to = "/free-voice-agent"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/trynow"
  status = 301

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
