name: staging
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for deployment'
        required: true
        default: 'Testing Lovable changes'

environment:
  name: staging
  url: https://powered-by-website-staging.web.app 