name: Deploy to Firebase Production

on:
  push:
    branches:
      - production

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/326818403042/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'windsurf-access-to-pwb-website@powered-by-website-redundancy.iam.gserviceaccount.com'

      - name: Deploy to Firebase Hosting
        uses: google-github-actions/deploy-firebase@6f28a593c41b2e4271cf9fd2f347d79c7e83e3d7
        with:
          channel_id: live
          project_id: powered-by-website-redundancy
