name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Deploy to Firebase Hosting with token
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting:powered-by-website-redundancy --token "${{ secrets.FIREBASE_DEPLOY_TOKEN }}"
          Fix Firebase deploy: add hosting site ID

