name: Deploy to Firebase Production

on:
  push:
    branches:
      - production

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/326818403042/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'windsurf-access-to-pwb-website@powered-by-website-redundancy.iam.gserviceaccount.com'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Get Current Deployed Version
        id: get_current
        run: |
          CURRENT_VERSION=$(gcloud firebase hosting sites describe powered-by-website-redundancy \
            --format="value(version.name)")
          echo "current_version=$CURRENT_VERSION" >> "$GITHUB_OUTPUT"

      - name: Deploy to Firebase Hosting
        id: deploy
        continue-on-error: true
        run: firebase deploy --only hosting --project powered-by-website-redundancy

      - name: Rollback if Deploy Failed
        if: steps.deploy.outcome == 'failure'
        run: |
          echo "⚠️ Deploy failed. Rolling back to: ${{ steps.get_current.outputs.current_version }}"
          gcloud firebase hosting versions clone \
            ${{ steps.get_current.outputs.current_version }} \
            --destination-site=powered-by-website-redundancy \
            --project powered-by-website-redundancy
