name: Deploy to Firebase Production

on:
  push:
    branches:
      - production

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for OIDC token
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2' # Using v2 as requested
        with:
          workload_identity_provider: 'projects/326818403042/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'windsurf-access-to-pwb-website@powered-by-website-redundancy.iam.gserviceaccount.com'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Get current live version
        id: get_live
        run: |
          ACCESS_TOKEN=$(gcloud auth print-access-token)
          LIVE_VERSION=$(curl -s -H "Authorization: Bearer $ACCESS_TOKEN" \
            "https://firebasehosting.googleapis.com/v1beta1/sites/powered-by-website-redundancy/releases?pageSize=1" \
            | jq -r '.releases[0].version.name')
          echo "live_version=$LIVE_VERSION" >> "$GITHUB_OUTPUT"

      - name: Deploy to Firebase Hosting
        id: deploy
        continue-on-error: true # Important for the rollback step
        run: firebase deploy --only hosting --project powered-by-website-redundancy

      - name: Rollback if Deploy Fails
        if: steps.deploy.outcome == 'failure'
        run: |
          echo "⚠️ Deploy failed. Rolling back to ${{ steps.get_live.outputs.live_version }}"
          ACCESS_TOKEN=$(gcloud auth print-access-token)
          curl -X POST -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"version\":\"${{ steps.get_live.outputs.live_version }}\"}" \
            "https://firebasehosting.googleapis.com/v1beta1/sites/powered-by-website-redundancy/releases"
