name: Deploy to Firebase Production

on:
  push:
    branches:
      - production # Deploys when a push is made to the 'production' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'


      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' # IMPORTANT: Ensure this secret is set in your GitHub repository settings
          channelId: live
          projectId: powered-by-website-redundancy
